source 'https://rubygems.org'
gem 'sinatra'
gem 'mysql2'
gem 'uber_api', :git => 'git://github.com/abhijeetkalyan/uber_api'
gem 'geocoder'
gem 'twilio-ruby'
gem 'pry'
gem 'pry-nav'
gem 'faraday'
gem 'faraday_middleware'
